### ISSUE TITLE
[Question] How are split points chosen for regression trees?

### ISSUE THREAD

**Issue by ben519** [gbm-developers/gbm3#134]
Suppose I choose my objective as "laplace" to minimize absolute loss. How are tree split points chosen?  Does gbm search for the split that reduces mae the most or does gbm always use mse to select split points?

**Comment by gregridgeway** [comment]
Always MSE, but the form of the working response changes depending on the
distribution you choose.

On Dec 18, 2016 6:49 PM, "Ben" <notifications@github.com> wrote:

Suppose I choose my objective as "laplace" to minimize absolute loss. How
are tree split points chosen? Does gbm search for the split that reduces
mae the most or does gbm always use mse to select split points?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gbm-developers/gbm/issues/134>, or mute the thread

**Comment by ben519** [comment]
Thanks Greg.  That would've been my guess, but I wasn't 100% sure since other packages offer multiple splitting criteria.  Related - if you could take a look at my question [here](http://stats.stackexchange.com/questions/252288/gradient-boosting-help-with-minimal-example) I would **really** appreciate it.
